name: Publish Docker Images

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build-and-publish:
    name: Build and publish Docker images to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and Publish to Registry
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: matthewfeickert/madgraph5-amc-nlo
        dockerfile: Dockerfile
        tags: latest,mg5amc2.7.2-python2.7
    - name: Build and Publish to Registry with Release Tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: matthewfeickert/madgraph5-amc-nlo
        dockerfile: Dockerfile
        tags: latest,latest-stable,mg5amc2.7.2-python2.7
        tag_with_ref: true

        https://launchpad.net/mg5amcnlo/2.0/2.7.x/+download/MG5_aMC_v2.7.2.tar.gz
